[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_GITHUB_TOKEN = "your_production_github_token"
  VITE_GITHUB_REPO_OWNER = "your_github_username"
  VITE_GITHUB_REPO_NAME = "hibrid-shopp-data"
  VITE_GITHUB_BRANCH = "main"

[context.deploy-preview.environment]
  VITE_GITHUB_TOKEN = "your_preview_github_token"
  VITE_GITHUB_REPO_OWNER = "your_github_username"
  VITE_GITHUB_REPO_NAME = "hibrid-shopp-data"
  VITE_GITHUB_BRANCH = "main"

[context.branch-deploy.environment]
  VITE_GITHUB_TOKEN = "your_branch_github_token"
  VITE_GITHUB_REPO_OWNER = "your_github_username"
  VITE_GITHUB_REPO_NAME = "hibrid-shopp-data"
  VITE_GITHUB_BRANCH = "main" 